version: '3.8'

services:

  nodejs_dev:
    build:
      context: nodejs
      args:
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /usr/share/nginx/front
    volumes:
      - ../front:/usr/share/nginx/front
    environment:
      - HOST=0.0.0.0
    command: tail -F anything
    user: "${ID_USER}:${ID_GROUP}"
    ports:
      - "9000:9000" # for vite dev websocket
    restart: unless-stopped
    profiles:
      - dev

  nginx_dev:
    build:
      context: nginx_dev
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    working_dir: /usr/share/nginx/front
    volumes:
      - ../front:/usr/share/nginx/front
    restart: unless-stopped
    ports:
      - ${PORT_NGINX}:80
    profiles:
      - dev
